name: ingest-and-verify-tiingo

on:
  workflow_dispatch:
    inputs:
      tickers:
        description: "Comma-separated tickers"
        default: "AAPL,NVDA,WMT,ALB"
        required: true
      start:
        description: "Start date (YYYY-MM-DD)"
        default: "1996-01-01"
        required: true
      end:
        description: "End date (YYYY-MM-DD, optional)"
        default: ""
        required: false

env:
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: ${{ github.workspace }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "pandas==2.2.3" >> requirements.txt
            echo "pyarrow==15.0.2" >> requirements.txt
            echo "pandas-datareader==0.10.0" >> requirements.txt
            pip install -r requirements.txt
          fi

      - name: Show inputs
        run: |
          echo "Tickers: ${{ github.event.inputs.tickers }}"
          echo "Start:   ${{ github.event.inputs.start }}"
          echo "End:     ${{ github.event.inputs.end }}"

      - name: Ingest from Tiingo → Supabase
        run: |
          set -e
          IFS=',' read -ra TKS <<< "${{ github.event.inputs.tickers }}"
          for T in "${TKS[@]}"; do
            T=$(echo "$T" | xargs)
            echo "=== MIGRATE $T ==="
            python scripts/migrate_lake_from_tiingo.py \
              --ticker "$T" \
              --start "${{ github.event.inputs.start }}" \
              $( [ -n "${{ github.event.inputs.end }}" ] && echo --end "${{ github.event.inputs.end }}" )
          done

      - name: Verify vs Tiingo (0.1% MAD)
        run: |
          set -e
          IFS=',' read -ra TKS <<< "${{ github.event.inputs.tickers }}"
          for T in "${TKS[@]}"; do
            T=$(echo "$T" | xargs)
            echo "=== VERIFY $T ==="
            python scripts/verify_raw_vs_tiingo.py --ticker "$T" --start "${{ github.event.inputs.start }}" --end "${{ github.event.inputs.end }}"
          done
