name: Daily scan + TP check

on:
  # Manual run
  workflow_dispatch:

  # Scheduled runs (UTC)
  schedule:
    # 10:30 ET ≈ 14:30 UTC (EDT)
    - cron: "30 14 * * 1-5"
    # 11:30 ET ≈ 15:30 UTC (EDT)
    - cron: "30 15 * * 1-5"
    # 12:30 ET ≈ 16:30 UTC (EDT)
    - cron: "30 16 * * 1-5"
    # Nightly hit check after close + buffer (~23:30 UTC)
    - cron: "30 23 * * 1-5"

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./scripts/requirements.txt

      - name: Run screener and write history
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Run scan and write pass files + history/logs under ./data/
          python ./scripts/run_and_log.py --universe sp500 --with-options
          # Also run the TP hit checker to update hit logs
          python ./scripts/check_hits.py

      # Keep downloadable artifacts for each run
      - name: Upload artifacts (CSV + logs)
        uses: actions/upload-artifact@v4
        with:
          name: pass-files
          path: |
            pass_tickers.csv
            pass_tickers_unadjusted.psv
            data/history/**
            data/logs/**
          if-no-files-found: warn
          retention-days: 7

      # Commit files back to the repo so Streamlit can read them
      - name: Commit history to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A data/ pass_tickers.csv pass_tickers_unadjusted.psv
          git commit -m "History update (auto)" || echo "Nothing to commit"
          git push
