name: Daily scan + TP check

on:
  # Click “Run workflow” in the Actions tab to start immediately
  workflow_dispatch:
    inputs:
      run_type:
        description: "What to run"
        required: true
        default: "both"
        type: choice
        options:
          - both
          - scan
          - check
  # UTC-only cron. You already picked these times.
  schedule:
    - cron: "17 1 * * 1-5"   # 00:44 UTC (your quick test slot)
    - cron: "30 15 * * 1-5"   # 11:30 ET (15:30 UTC)
    - cron: "30 16 * * 1-5"   # 12:30 ET (16:30 UTC)
    - cron: "30 23 * * 1-5"   # nightly hit check ~ after close (23:30 UTC)

permissions:
  contents: write   # allow the job to commit files to the repo

env:
  PYTHONUNBUFFERED: "1"
  TZ: America/New_York   # for logs printed by our scripts

jobs:
  scan:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_type != 'check' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run screener and save results
        run: |
          python scripts/run_and_log.py --universe sp500 --with-options

      - name: Upload scan artifact (CSV)
        uses: actions/upload-artifact@v4
        with:
          name: pass-files
          path: |
            data/history/**

  check:
    needs: [scan]
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_type != 'scan' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Update TP-hit status
        run: |
          python scripts/check_hits.py

      - name: Upload hit-check artifact
        uses: actions/upload-artifact@v4
        with:
          name: hit-check
          path: |
            data/hits/**

