name: Scheduled Swing Scan

on:
  # Manual run button
  workflow_dispatch:
  # Cron schedule — UTC (ET 10:30/11:30/12:30 + nightly check ~ 19:30 ET)
  schedule:
    - cron: "30 14 * * 1-5"   # 10:30 ET (EDT)
    - cron: "30 15 * * 1-5"   # 11:30 ET (EDT)
    - cron: "30 16 * * 1-5"   # 12:30 ET (EDT)
    - cron: "30 23 * * 1-5"   # Nightly hit check

permissions:
  contents: write   # needed to commit the CSV/log updates

jobs:
  run-and-log:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run screener and write history files
        run: |
          python scripts/run_and_log.py --universe sp500 --with-options || true

      - name: Commit history updates (pass_*.csv, outcomes.csv, logs)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only if they exist
          git add -A data/history/*.csv 2>/dev/null || true
          git add -A data/logs/*.log     2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            # Avoid non-fast-forward errors if main moved
            git pull --rebase origin "${GITHUB_REF_NAME}"
            git commit -m "update history $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin HEAD:"${GITHUB_REF_NAME}"
          fi
