name: Daily scan + TP check

on:
  workflow_dispatch:
  schedule:
    # ---- all UTC ----
    # 10:30 ET ≈ 14:30 UTC (EDT), 11:30 ET ≈ 15:30, 12:30 ET ≈ 16:30
    - cron: "30 14 * * 1-5"
    - cron: "30 15 * * 1-5"
    - cron: "30 16 * * 1-5"
    # nightly outcome refresh after US close + buffer (~23:30 UTC)
    - cron: "30 23 * * 1-5"

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/requirements.txt

      - name: Run screener and write history
        env:
          GH_ACTOR: ${{ github.actor }}
        run: |
          python ./scripts/run_and_log.py --universe sp500 --with-options

      - name: Upload artifacts (CSV + logs)  # optional
        uses: actions/upload-artifact@v4
        with:
          name: daily-scan
          path: |
            data/history/*.csv
            data/logs/*.txt
          if-no-files-found: ignore

      - name: Commit history to repo
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/history/*.csv data/logs/*.txt || true
          git commit -m "history: daily scan $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "nothing to commit"
          git push

  check:
    runs-on: ubuntu-latest
    needs: scan        # ensure pass_*.csv are pushed first
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r scripts/requirements.txt

      - name: Compute/refresh outcomes.csv
        run: |
          python ./scripts/check_hits.py

      - name: Commit outcomes.csv
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/history/outcomes.csv || true
          git commit -m "history: update outcomes $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "nothing to commit"
          git push


