name: Daily scan + TP check

on:
  workflow_dispatch: {}        # Run by hand
  schedule:                    # (keeps your timers too)
    # 10:30 / 11:30 / 12:30 ET  (cron is UTC)
    - cron: "30 14 * * 1-5"
    - cron: "30 15 * * 1-5"
    - cron: "30 16 * * 1-5"
    # Nightly ~ 23:30 UTC for TP-hit check
    - cron: "30 23 * * 1-5"

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # allow commit to the repo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r ./scripts/requirements.txt

      - name: Run screener and write history
        run: |
          python ./scripts/run_and_log.py --universe sp500 --with-options
        env:
          TZ: America/New_York

      - name: Upload artifacts (CSV + logs)
        uses: actions/upload-artifact@v4
        with:
          name: pass-files
          path: |
            pass_tickers.csv
            pass_tickers_unadjusted.psv
            data/history/**/*.psv
            data/history/**/*.csv
            data/logs/**/*.txt
          if-no-files-found: warn

      - name: Commit history to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "History update (auto)"
          file_pattern: |
            data/history/**/*.psv
            data/history/**/*.csv
            data/logs/**/*.txt
