name: Daily scan + TP check

on:
  workflow_dispatch:
    inputs:
      run_scan:
        description: "Run the scanner now"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
      run_check:
        description: "Run the TP hit checker now"
        required: true
        default: "true"
        type: choice
        options: ["true","false"]
  schedule:
    # UTC times (no DST). Tweak as needed.
    - cron: "30 14 * * 1-5"   # 10:30 ET
    - cron: "30 15 * * 1-5"   # 11:30 ET
    - cron: "30 16 * * 1-5"   # 12:30 ET
    - cron: "30 23 * * 1-5"   # 18:30 ET (post-close checks)

jobs:
  scan:
    if: github.event_name == 'schedule' || inputs.run_scan == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install scan dependencies
        run: |
          python -m pip install -r ./scripts/requirements.txt

      - name: Run screener and save results
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./scripts/run_and_log.py --universe sp500 --with-options
          # Commit any new/updated files under data/
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "history: add scan $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push

  check:
    needs: scan
    if: github.event_name == 'schedule' || inputs.run_check == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install check dependencies
        run: |
          python -m pip install -r ./scripts/requirements.txt

      - name: Check TP hits and update summaries
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./scripts/check_hits.py
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "hits: refresh $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push


