name: Daily scan + TP check

on:
  workflow_dispatch: {}
  schedule:
    # 10:30 / 11:30 / 12:30 ET (convert to UTC for your timezone/DST as needed)
    - cron: "30 14 * * 1-5"
    - cron: "30 15 * * 1-5"
    - cron: "30 16 * * 1-5"
    # nightly outcomes scoring (~ after US close)
    - cron: "30 23 * * 1-5"

permissions:
  contents: write

jobs:
  scan:
    name: Run screener and write history
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./scripts/requirements.txt

      - name: Run screener and write history
        env:
          TZ: America/New_York
        run: |
          python ./scripts/run_and_log.py --universe sp500 --with-options

      - name: Upload artifacts (CSV + logs)
        uses: actions/upload-artifact@v4
        with:
          name: run_${{ github.run_id }}
          path: |
            data/history/*.csv
            data/logs/*.txt

      - name: Commit history to repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data/history/*.csv || true
          git add data/logs/*.txt || true
          git commit -m "History update [skip ci]" || echo "No changes to commit"
          git push

  check:
    name: Score outcomes
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps for scoring
        run: |
          python -m pip install --upgrade pip
          python -m pip install yfinance pandas numpy

      - name: Run scorer
        run: |
          python ./scripts/score_history.py

      - name: Commit outcomes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data/outcomes/outcomes.csv || true
          git commit -m "Update outcomes [skip ci]" || echo "No changes to commit"
          git push

