name: Scheduled Scanner

on:
  schedule:
    # NOTE: GitHub Actions cron is UTC only (no DST). Adjust if needed.
    # 10:30 ET ≈ 14:30 UTC (EDT), 11:30 ET ≈ 15:30 UTC, 12:30 ET ≈ 16:30 UTC
    - cron: "55 00 * * 1-5"
    - cron: "30 15 * * 1-5"
    - cron: "30 16 * * 1-5"
    # Nightly hit check ~ 23:30 UTC (after US close + buffer)
    - cron: "30 23 * * 1-5"

  workflow_dispatch: {}

permissions:
  contents: write  # allow committing history files

jobs:
  run-scan:
    if: github.event.schedule == '30 14 * * 1-5' || github.event.schedule == '30 15 * * 1-5' || github.event.schedule == '30 16 * * 1-5' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scan and append to history
        run: |
          python run_and_log.py

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name  "github-actions"
          git add history/*
          git commit -m "scan: $(date -u +'%Y-%m-%d %H:%M:%S %Z')" || echo "No changes to commit"
          git push

  nightly-check:
    if: github.event.schedule == '30 23 * * 1-5'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check hits and update history
        run: |
          python check_hits.py

      - name: Commit results
        run: |
          git config user.email "actions@github.com"
          git config user.name  "github-actions"
          git add history/*
          git commit -m "nightly hit-check: $(date -u +'%Y-%m-%d %H:%M:%S %Z')" || echo "No changes to commit"
          git push
