# Basic dependency import smoke test
name: smoke
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install minimal deps (smoke)
        run: |
          python -m pip install --upgrade pip
          for i in 1 2 3; do
            pip install --only-binary=:all: -r requirements-smoke.txt && break || sleep 5
          done
      - name: Import check
        run: |
          python - <<'PY'
          import streamlit, yfinance, pandas, numpy, pyarrow, bs4, lxml, requests
          import data_lake.ingest, data_lake.membership, data_lake.storage, data_lake.provider
          print("ok")
          PY
