name: tests

on:
  push: {}
  pull_request: {}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -r requirements-smoke.txt || true
          pip install pytest
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Run tests
        run: pytest -q
