name: verify-raw

on:
  schedule:
    - cron: "17 5 * * 1-5"
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt
      - name: Verify sample tickers vs Yahoo
        run: |
          python scripts/verify_raw_vs_yahoo.py --ticker NVDA --start 2020-01-01 --end 2020-12-31
          python scripts/verify_raw_vs_yahoo.py --ticker WMT  --start 2020-01-01 --end 2020-12-31
          python scripts/verify_raw_vs_yahoo.py --ticker ALB  --start 2025-03-01 --end 2025-03-10
